import TempImg from "../assets/tempimg.jpg";

export const dummyImg = [
  {
    id: 1,
    image: TempImg,
    title: "Very Long Name Restaurants Number 1 in List",
    star1: "fa-solid fa-star",
    star2: "fa-solid fa-star",
    star3: "fa-solid fa-star",
    star4: "fa-solid fa-star",
    star5: "fa-regular fa-star",
    category: "THAI",
    price: "$$$",
    door: "Open",
    learn: "Learn More",
  },
  {
    id: 2,
    image: TempImg,
    title: "Restaurants",
    star1: "fa-solid fa-star",
    star2: "fa-solid fa-star",
    star3: "fa-solid fa-star",
    star4: "fa-regular fa-star",
    star5: "fa-regular fa-star",
    category: "THAI",
    price: "$$$",
    door: "Open",
    learn: "Learn More",
  },
  {
    id: 3,
    image: TempImg,
    title: "Restaurants",
    star1: "fa-solid fa-star",
    star2: "fa-solid fa-star",
    star3: "fa-solid fa-star",
    star4: "fa-solid fa-star-half-stroke",
    star5: "fa-regular fa-star",
    category: "THAI",
    price: "$$$",
    door: "Open",
    learn: "Learn More",
  },
  {
    id: 4,
    image: TempImg,
    title: "Restaurants",
    star1: "fa-solid fa-star",
    star2: "fa-solid fa-star",
    star3: "fa-solid fa-star",
    star4: "fa-solid fa-star-half-stroke",
    star5: "fa-regular fa-star",
    category: "THAI",
    price: "$$$",
    door: "Open",
    learn: "Learn More",
  },
  {
    id: 5,
    image: TempImg,
    title: "Restaurants",
    star1: "fa-solid fa-star",
    star2: "fa-solid fa-star",
    star3: "fa-solid fa-star",
    star4: "fa-regular fa-star",
    star5: "fa-regular fa-star",
    category: "THAI",
    price: "$$$",
    door: "Open",
    learn: "Learn More",
  },
];
